<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2.3 Bayes discriminant rule | Multivariate Statistics</title>
  <meta name="description" content="The lecture notes for MATH3030/4068: Multivariate Analysis / Applied Multivariate Statistics" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="2.3 Bayes discriminant rule | Multivariate Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="The lecture notes for MATH3030/4068: Multivariate Analysis / Applied Multivariate Statistics" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2.3 Bayes discriminant rule | Multivariate Statistics" />
  
  <meta name="twitter:description" content="The lecture notes for MATH3030/4068: Multivariate Analysis / Applied Multivariate Statistics" />
  

<meta name="author" content="Prof. Richard Wilkinson" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="2-2-lda-ML.html"/>
<link rel="next" href="2-4-FLDA.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied multivariate statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="1-cca.html"><a href="1-cca.html"><i class="fa fa-check"></i><b>1</b> Canonical Correlation Analysis (CCA)</a><ul>
<li class="chapter" data-level="1.1" data-path="1-1-cca1.html"><a href="1-1-cca1.html"><i class="fa fa-check"></i><b>1.1</b> The first pair of canonical variables</a><ul>
<li class="chapter" data-level="1.1.1" data-path="1-1-cca1.html"><a href="1-1-cca1.html#the-first-canonical-components"><i class="fa fa-check"></i><b>1.1.1</b> The first canonical components</a></li>
<li class="chapter" data-level="1.1.2" data-path="1-1-cca1.html"><a href="1-1-cca1.html#premcca"><i class="fa fa-check"></i><b>1.1.2</b> Example: Premier league football</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="1-2-the-full-set-of-canonical-correlations.html"><a href="1-2-the-full-set-of-canonical-correlations.html"><i class="fa fa-check"></i><b>1.2</b> The full set of canonical correlations</a><ul>
<li class="chapter" data-level="1.2.1" data-path="1-2-the-full-set-of-canonical-correlations.html"><a href="1-2-the-full-set-of-canonical-correlations.html#example-continued"><i class="fa fa-check"></i><b>1.2.1</b> Example continued</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="1-3-properties.html"><a href="1-3-properties.html"><i class="fa fa-check"></i><b>1.3</b> Properties</a><ul>
<li class="chapter" data-level="1.3.1" data-path="1-3-properties.html"><a href="1-3-properties.html#connection-with-linear-regression-when-q1"><i class="fa fa-check"></i><b>1.3.1</b> Connection with linear regression when <span class="math inline">\(q=1\)</span></a></li>
<li class="chapter" data-level="1.3.2" data-path="1-3-properties.html"><a href="1-3-properties.html#invarianceequivariance-properties-of-cca"><i class="fa fa-check"></i><b>1.3.2</b> Invariance/equivariance properties of CCA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-iv-classification-and-clustering.html"><a href="part-iv-classification-and-clustering.html"><i class="fa fa-check"></i>Part IV: Classification and Clustering</a></li>
<li class="chapter" data-level="2" data-path="2-lda.html"><a href="2-lda.html"><i class="fa fa-check"></i><b>2</b> Discriminant analysis</a><ul>
<li class="chapter" data-level="2.1" data-path="2-1-intro-delete-title-later.html"><a href="2-1-intro-delete-title-later.html"><i class="fa fa-check"></i><b>2.1</b> Intro - delete title later</a><ul>
<li class="chapter" data-level="2.1.1" data-path="2-1-intro-delete-title-later.html"><a href="2-1-intro-delete-title-later.html#linear-discriminant-analysis"><i class="fa fa-check"></i><b>2.1.1</b> Linear discriminant analysis</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="2-2-lda-ML.html"><a href="2-2-lda-ML.html"><i class="fa fa-check"></i><b>2.2</b> Maximum likelihood (ML) discriminant rule</a><ul>
<li class="chapter" data-level="2.2.1" data-path="2-2-lda-ML.html"><a href="2-2-lda-ML.html#multivariate-gaussian-populations"><i class="fa fa-check"></i><b>2.2.1</b> Multivariate Gaussian populations</a></li>
<li class="chapter" data-level="2.2.2" data-path="2-2-lda-ML.html"><a href="2-2-lda-ML.html#sample-lda"><i class="fa fa-check"></i><b>2.2.2</b> The sample ML discriminant rule</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="2-3-lda-Bayes.html"><a href="2-3-lda-Bayes.html"><i class="fa fa-check"></i><b>2.3</b> Bayes discriminant rule</a><ul>
<li class="chapter" data-level="2.3.1" data-path="2-3-lda-Bayes.html"><a href="2-3-lda-Bayes.html#example-lda-using-the-iris-data"><i class="fa fa-check"></i><b>2.3.1</b> Example: LDA using the Iris data</a></li>
<li class="chapter" data-level="2.3.2" data-path="2-3-lda-Bayes.html"><a href="2-3-lda-Bayes.html#links-between-lda-fishers-discriminant-analysis-cca-and-linear-models"><i class="fa fa-check"></i><b>2.3.2</b> Links between LDA, Fisher’s Discriminant Analysis, CCA, and linear models</a></li>
<li class="chapter" data-level="2.3.3" data-path="2-3-lda-Bayes.html"><a href="2-3-lda-Bayes.html#quadratic-discriminant-analysis-qda"><i class="fa fa-check"></i><b>2.3.3</b> Quadratic Discriminant Analysis (QDA)</a></li>
<li class="chapter" data-level="2.3.4" data-path="2-3-lda-Bayes.html"><a href="2-3-lda-Bayes.html#could-do-prediction-accuracy-here"><i class="fa fa-check"></i><b>2.3.4</b> Could do prediction accuracy here?</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="2-4-FLDA.html"><a href="2-4-FLDA.html"><i class="fa fa-check"></i><b>2.4</b> Fisher’s linear discriminant rule</a></li>
<li class="chapter" data-level="2.5" data-path="2-5-probability-of-misclassification.html"><a href="2-5-probability-of-misclassification.html"><i class="fa fa-check"></i><b>2.5</b> Probability of misclassification</a></li>
<li class="chapter" data-level="2.6" data-path="2-6-mnist.html"><a href="2-6-mnist.html"><i class="fa fa-check"></i><b>2.6</b> MNIST</a></li>
<li class="chapter" data-level="2.7" data-path="2-7-computer-tasks.html"><a href="2-7-computer-tasks.html"><i class="fa fa-check"></i><b>2.7</b> Computer tasks</a></li>
<li class="chapter" data-level="2.8" data-path="2-8-exercises.html"><a href="2-8-exercises.html"><i class="fa fa-check"></i><b>2.8</b> Exercises</a></li>
</ul></li>
<li class="divider"></li>
<li> <a href="https://rich-d-wilkinson.github.io/teaching.html" target="blank">University of Nottingham</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Multivariate Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="lda-Bayes" class="section level2">
<h2><span class="header-section-number">2.3</span> Bayes discriminant rule</h2>
<p>In the previous section, we implicitly assumed that each subject is equally likely to be from any of the <span class="math inline">\(g\)</span> populations. This is the simplest case but is an unrealistic assumption in practice.</p>
<p>For example, suppose we want to classify photos on the internet as either being a photo of <em>Bill Evans</em> or <em>not Bill Evans</em>. Most photos on the internet are not of Bill Evans, and so we want to take this into account in the classifier, i.e., we want to take the base rate of occurence of each population into account.</p>
<p>Suppose <em>a priori</em> that the probability an observation is from population <span class="math inline">\(k\)</span> is <span class="math inline">\(\pi_k\)</span>, with
<span class="math display">\[\sum_{k=1}^g \pi_k=1.\]</span>
Then given a probability model <span class="math inline">\(f_k(\mathbf x)\)</span> for observations <span class="math inline">\(\mathbf x\)</span> from population <span class="math inline">\(k\)</span>, our posterior probability for observation <span class="math inline">\(\mathbf x\)</span> being from population <span class="math inline">\(k\)</span> is
<span class="math display">\[{\mathbb{P}}(y=k \mid \mathbf x) = \frac{f_k(\mathbf x)\pi_k}{\sum_{j=1}^g f_k(\mathbf x)\pi_k}\]</span>
by Bayes theorem.</p>

<div class="definition">
<span id="def:bayesclassifier" class="definition"><strong>Definition 2.3  </strong></span>The Bayes classifier assigns <span class="math inline">\(\mathbf x\)</span> to the population for which the posterior probability is highest:
<span class="math display">\[d^{Bayes}(\mathbf x) =\arg \max_k {\mathbb{P}}(y=k \mid \mathbf x).\]</span>
</div>

<p>As before, if we assume each population has a multivariate normal distribution, then this simplifies.</p>

<div class="proposition">
<p><span id="prp:ldabayes" class="proposition"><strong>Proposition 2.3  </strong></span>If cases in population <span class="math inline">\(\Pi_k\)</span> have a <span class="math inline">\(N_p({\boldsymbol{\mu}}_k,\boldsymbol{\Sigma})\)</span> distribution, then the <strong>Bayes</strong> discriminant rule is
<span class="math display">\[d(\mathbf x)= \arg\min_{k} \frac{1}{2}(\mathbf x-{\boldsymbol{\mu}}_k)^\top \boldsymbol{\Sigma}^{-1} (\mathbf x-{\boldsymbol{\mu}}_k)- \log \pi_k.\]</span></p>
Equivalently, if
<span class="math display">\[\delta_k(\mathbf x) = {\boldsymbol{\mu}}_k^\top \boldsymbol{\Sigma}^{-1} \mathbf x-\frac{1}{2}{\boldsymbol{\mu}}_k^\top \Sigma^{-1} {\boldsymbol{\mu}}_k +\log \pi_k\]</span>
then
<span class="math display">\[d(\mathbf x) = \arg \max \delta_k(\mathbf x).\]</span>
I.e. this is a linear discriminant rule.
</div>


<div class="proof">
<p> <span class="proof"><em>Proof. </em></span> See the exercises….?</p>
</div>

<p>In practice, we may not know the population probabilities <span class="math inline">\(\pi_k\)</span>. If so, we can estimate them from the data using
<span class="math display">\[\hat{\pi}_k = \frac{n_k}{n}\]</span>
and substitute <span class="math inline">\(\hat{\pi}_k\)</span> for <span class="math inline">\(\pi_k\)</span> (as well as substituting <span class="math inline">\(\hat{{\boldsymbol{\mu}}}_k\)</span>, <span class="math inline">\(\widehat{\boldsymbol{\Sigma}}\)</span> etc).</p>
<p>If we set <span class="math inline">\(\pi_k = \frac{1}{g}\)</span> then the Bayes discriminant rule is the same as the ML discriminant rule. The <code>MASS</code> implementation <code>lda</code> uses the Bayes discriminant rule, but gives you the option of setting <span class="math inline">\(\pi_k\)</span> if known, but otherwise estimates the class probabilities.</p>
<div id="example-lda-using-the-iris-data" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Example: LDA using the Iris data</h3>
<p>Let’s consider doing LDA with the iris data. To begin with, lets use just the setosa and virginica species so that we only have <span class="math inline">\(g=2\)</span> populations. We will also just use the sepal measurements so that <span class="math inline">\(p=2\)</span>. If we plot the data, we can see that the two populations should be easy to classify using just these two measurements:</p>
<p><img src="09-lda_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>The sample means and variances for each group are</p>
<pre><code>##              Sepal.Length Sepal.Width
## Sepal.Length   0.26968971  0.09845898
## Sepal.Width    0.09845898  0.12637443</code></pre>
<pre><code>##              Sepal.Length Sepal.Width
## Sepal.Length    0.2642959   0.0964898
## Sepal.Width     0.0964898   0.1238469
## attr(,&quot;means&quot;)
##           Sepal.Length Sepal.Width
## setosa           5.006       3.428
## virginica        6.588       2.974</code></pre>
<pre><code>## Warning: package &#39;vcvComp&#39; was built under R version 3.6.2</code></pre>
<pre><code>##           [,1]      [,2]
## [1,] 0.2642959 0.0964898
## [2,] 0.0964898 0.1238469</code></pre>
<pre><code>##              Sepal.Length Sepal.Width
## Sepal.Length     1.251362   -0.359114
## Sepal.Width     -0.359114    0.103058</code></pre>
<pre><code>## , , setosa
## 
##              Sepal.Length Sepal.Width
## Sepal.Length   0.12424898  0.09921633
## Sepal.Width    0.09921633  0.14368980
## 
## , , virginica
## 
##              Sepal.Length Sepal.Width
## Sepal.Length   0.40434286  0.09376327
## Sepal.Width    0.09376327  0.10400408</code></pre>
<p><span class="math display">\[\begin{eqnarray*}
\bar{\mathbf x}_s = \begin{pmatrix}5.01 \\3.43 \\\end{pmatrix} &amp;\qquad&amp; \bar{\mathbf x}_v = \begin{pmatrix}6.59 \\2.97 \\\end{pmatrix} \\
\mathbf S_s = \begin{pmatrix}0.124&amp;0.0992 \\0.0992&amp;0.144 \\\end{pmatrix} &amp;\qquad&amp; \mathbf S_v =\begin{pmatrix}0.404&amp;0.0938 \\0.0938&amp;0.104 \\\end{pmatrix}
\end{eqnarray*}\]</span>
where the <span class="math inline">\(s\)</span> subscript gives the values for setosa, and <span class="math inline">\(v\)</span> for virginica.</p>
<p>We have data on <span class="math inline">\(n=50\)</span> flowers in each population. Hence,
<span class="math display">\[\begin{eqnarray*}
\widehat{\boldsymbol{\Sigma}} &amp;=&amp; \frac{1}{50+50-2} \left(50 \mathbf S_s + 50 \mathbf S_v \right)= \begin{pmatrix}0.27&amp;0.0985 \\0.0985&amp;0.126 \\\end{pmatrix}, \\
\bar{\mathbf x}_s - \bar{\mathbf x}_v &amp;=&amp; \begin{pmatrix}-1.58 \\0.454 \\\end{pmatrix}, \\
\hat{\mathbf h} &amp;=&amp; \frac{1}{2} (\bar{\mathbf x}_s + \bar{\mathbf x}_v) = \begin{pmatrix}5.797 \\3.201 \\\end{pmatrix},
\end{eqnarray*}\]</span>
and
<span class="math display">\[\hat{\mathbf a} = \widehat{\boldsymbol{\Sigma}}^{-1} (\bar{\mathbf x}_s - \bar{\mathbf x}_v) = \begin{pmatrix}5.18&amp;-4.04 \\-4.04&amp;11.1 \\\end{pmatrix} \begin{pmatrix}-1.58 \\0.454 \\\end{pmatrix} = \begin{pmatrix}-10.031 \\11.407 \\\end{pmatrix}.\]</span></p>
<p>The sample ML discriminant rule allocates a new observation <span class="math inline">\(\mathbf x= (z_1, z_2)^\top\)</span> to <span class="math inline">\(\Pi_{\mbox{setosa}}\)</span> if and only if
<span class="math display">\[ \hat{\mathbf a}^\top (\mathbf x- \hat{\mathbf h}) = \begin{pmatrix}-10.031&amp;11.407 \\\end{pmatrix} \begin{pmatrix} z_1 - 5.797 \\ z_2 - 3.201 \end{pmatrix} &gt; 0.\]</span></p>
<p>If we draw on the line defined by
<span class="math display">\[\mathbf a^\top (\mathbf x-\mathbf h)=0\]</span>
which can be written as
<span class="math display">\[x_2 = \frac{1}{a_2}(\mathbf a^\top\mathbf h-a_1x_1) = -1.8963517 - -0.8793085 x_1\]</span>
we can see this line clearly separates the two species of iris.</p>
<p><img src="09-lda_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>For example, if an iris had a sepal length of 5.8 and a sepal width of 2.5 then</p>
<p><span class="math display">\[ \hat{\mathbf a}^\top (\mathbf x- \hat{\mathbf h}) = \begin{pmatrix}-10.031&amp;11.407 \\\end{pmatrix} \begin{pmatrix} 5.8 - 5.797 \\ 2.5 - 3.201 \end{pmatrix} =-8.0267032 &lt; 0,\]</span>
and so we would allocate this iris to virginia.</p>
<p>As always, there is an R command to do this work for us. The command is called <code>lda</code> and it is in the <code>MASS</code> R package.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1"><span class="kw">library</span>(MASS)</a>
<a class="sourceLine" id="cb29-2" data-line-number="2">iris.lda1 &lt;-<span class="st"> </span><span class="kw">lda</span>(Species <span class="op">~</span><span class="st"> </span>., iris3)</a>
<a class="sourceLine" id="cb29-3" data-line-number="3"></a>
<a class="sourceLine" id="cb29-4" data-line-number="4"><span class="co"># lda(Species ~ Sepal.Length+Sepal.Width, iris2) </span></a>
<a class="sourceLine" id="cb29-5" data-line-number="5">  <span class="co">#  does the same thing</span></a>
<a class="sourceLine" id="cb29-6" data-line-number="6">iris.lda1</a></code></pre></div>
<pre><code>## Call:
## lda(Species ~ ., data = iris3)
## 
## Prior probabilities of groups:
##    setosa virginica 
##       0.5       0.5 
## 
## Group means:
##           Sepal.Length Sepal.Width
## setosa           5.006       3.428
## virginica        6.588       2.974
## 
## Coefficients of linear discriminants:
##                    LD1
## Sepal.Length  2.208596
## Sepal.Width  -2.511742</code></pre>
<p>You can see that this has computed the group means, and the lda coefficients. The coefficients are different to the ones we compute for <span class="math inline">\(\mathbf a\)</span>, but have the same ratio, which is all that matters for us.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1">iris.coef &lt;-<span class="st"> </span><span class="kw">coef</span>(iris.lda1)</a>
<a class="sourceLine" id="cb31-2" data-line-number="2">iris.coef[<span class="dv">1</span>]<span class="op">/</span>iris.coef[<span class="dv">2</span>]</a></code></pre></div>
<pre><code>## [1] -0.8793085</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1">a[<span class="dv">1</span>]<span class="op">/</span>a[<span class="dv">2</span>]</a></code></pre></div>
<pre><code>## [1] -0.8793085</code></pre>
<p>How to plot and visualize the predictions??</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1">iris.pred &lt;-<span class="st"> </span><span class="kw">predict</span>(iris.lda1)</a></code></pre></div>
</div>
<div id="links-between-lda-fishers-discriminant-analysis-cca-and-linear-models" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Links between LDA, Fisher’s Discriminant Analysis, CCA, and linear models</h3>
<p>Same as linear regression….</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" data-line-number="1">iris3<span class="op">$</span>pm1 &lt;-<span class="st"> </span><span class="kw">as.integer</span>(iris3<span class="op">$</span>Species)<span class="op">-</span><span class="dv">2</span> </a>
<a class="sourceLine" id="cb36-2" data-line-number="2"><span class="co"># convert to +1 and -1</span></a>
<a class="sourceLine" id="cb36-3" data-line-number="3">iris3.lm &lt;-<span class="st"> </span><span class="kw">lm</span>(pm1<span class="op">~</span>Sepal.Length<span class="op">+</span>Sepal.Width, iris3)</a>
<a class="sourceLine" id="cb36-4" data-line-number="4"><span class="kw">coef</span>(iris3.lm)[<span class="dv">2</span>]<span class="op">/</span><span class="kw">coef</span>(iris3.lm)[<span class="dv">3</span>]</a></code></pre></div>
<pre><code>## Sepal.Length 
##   -0.8793085</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1">iris3<span class="op">$</span>M1 &lt;-<span class="st"> </span>(<span class="kw">as.integer</span>(iris3<span class="op">$</span>Species)<span class="op">-</span><span class="dv">1</span>)<span class="op">/</span><span class="dv">2</span> </a>
<a class="sourceLine" id="cb38-2" data-line-number="2">iris3<span class="op">$</span>M2 &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span>iris3<span class="op">$</span>M1</a>
<a class="sourceLine" id="cb38-3" data-line-number="3"></a>
<a class="sourceLine" id="cb38-4" data-line-number="4">X &lt;-<span class="st"> </span>iris3[,<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]</a>
<a class="sourceLine" id="cb38-5" data-line-number="5">Y &lt;-<span class="st"> </span><span class="kw">cbind</span>(iris3<span class="op">$</span>M1, iris3<span class="op">$</span>M2)</a>
<a class="sourceLine" id="cb38-6" data-line-number="6"><span class="kw">library</span>(CCA)</a>
<a class="sourceLine" id="cb38-7" data-line-number="7"><span class="kw">cc</span>(X,Y)</a></code></pre></div>
<p>The output also includes the estimate of the prior probabilities for the two species, which are estimated to be
<span class="math display">\[\hat{\pi}_s = \frac{1}{2}, \quad \hat{\pi}_v = \frac{1}{2}\]</span>
as there were 50 irises from each population in the training data.</p>
<p>We can make predictions about new points:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1">z=<span class="kw">data.frame</span>(<span class="dt">Sepal.Length=</span><span class="fl">5.8</span>, <span class="dt">Sepal.Width=</span><span class="fl">2.5</span>)</a>
<a class="sourceLine" id="cb39-2" data-line-number="2"><span class="kw">predict</span>(iris.lda1, z)</a></code></pre></div>
<pre><code>## $class
## [1] virginica
## Levels: setosa versicolor virginica
## 
## $posterior
##         setosa virginica
## 1 0.0002771946 0.9997228
## 
## $x
##        LD1
## 1 1.767357</code></pre>
<p>and in this case it gives us the</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1"><span class="kw">library</span>(mvtnorm)</a></code></pre></div>
<pre><code>## Warning: package &#39;mvtnorm&#39; was built under R version 3.6.2</code></pre>
<pre><code>## 
## Attaching package: &#39;mvtnorm&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:mixtools&#39;:
## 
##     dmvnorm, rmvnorm</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" data-line-number="1">l_set=mvtnorm<span class="op">::</span><span class="kw">dmvnorm</span>(z, <span class="dt">mean =</span> xbar_set, <span class="dt">sigma =</span> S_set)</a>
<a class="sourceLine" id="cb45-2" data-line-number="2">l_vir=mvtnorm<span class="op">::</span><span class="kw">dmvnorm</span>(z, <span class="dt">mean =</span> xbar_vir, <span class="dt">sigma =</span> S_vir)</a>
<a class="sourceLine" id="cb45-3" data-line-number="3"><span class="kw">c</span>(l_set,l_vir)<span class="op">/</span>(l_set<span class="op">+</span>l_vir)</a></code></pre></div>
<pre><code>##         1         1 
## 3.513e-09 1.000e+00</code></pre>
<p>Note that we could also</p>
<div id="using-the-entire-dataset" class="section level4">
<h4><span class="header-section-number">2.3.2.1</span> Using the entire dataset</h4>
<p>Lets now use all 150 observations, and all 4 measurements on each.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1">lda.iris &lt;-<span class="st"> </span><span class="kw">lda</span>(Species <span class="op">~</span><span class="st"> </span>.,iris)</a>
<a class="sourceLine" id="cb47-2" data-line-number="2">lda.iris </a></code></pre></div>
<pre><code>## Call:
## lda(Species ~ ., data = iris)
## 
## Prior probabilities of groups:
##     setosa versicolor  virginica 
##  0.3333333  0.3333333  0.3333333 
## 
## Group means:
##            Sepal.Length Sepal.Width Petal.Length Petal.Width
## setosa            5.006       3.428        1.462       0.246
## versicolor        5.936       2.770        4.260       1.326
## virginica         6.588       2.974        5.552       2.026
## 
## Coefficients of linear discriminants:
##                     LD1         LD2
## Sepal.Length  0.8293776  0.02410215
## Sepal.Width   1.5344731  2.16452123
## Petal.Length -2.2012117 -0.93192121
## Petal.Width  -2.8104603  2.83918785
## 
## Proportion of trace:
##    LD1    LD2 
## 0.9912 0.0088</code></pre>
<p>Comment on both LDA directions…………??????????</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" data-line-number="1"><span class="kw">plot</span>(lda.iris, <span class="dt">col =</span> <span class="kw">as.integer</span>(iris<span class="op">$</span>Species))</a></code></pre></div>
<p><img src="09-lda_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>As you can see, there are three distinct groups with some overlap between virginica and versicolor. Plotting again, but adding the code dimen = 1 will only plot in one dimension (LD1). Think of it as a projection of the data onto LD1 with a histogram of that data.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" data-line-number="1"><span class="kw">plot</span>(lda.iris, <span class="dt">dimen =</span> <span class="dv">1</span>, <span class="dt">type =</span> <span class="st">&quot;b&quot;</span>)</a></code></pre></div>
<p><img src="09-lda_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" data-line-number="1"><span class="kw">library</span>(klaR)</a>
<a class="sourceLine" id="cb51-2" data-line-number="2"><span class="kw">partimat</span>(Species <span class="op">~</span><span class="st"> </span>Sepal.Length <span class="op">+</span><span class="st"> </span>Sepal.Width <span class="op">+</span><span class="st"> </span>Petal.Length <span class="op">+</span><span class="st"> </span>Petal.Width, <span class="dt">data=</span>iris, <span class="dt">method=</span><span class="st">&quot;lda&quot;</span>)</a></code></pre></div>
<p><img src="09-lda_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<!--##### Example: Student marks

Consider the G11PRB and G11STA module marks for $n_1 = 98$ students on G100 and $n_2 = 46$ students on G103.  The sample means and variances for each group are given by
\begin{eqnarray*}
\bar{\bx}_1 = \begin{pmatrix} 60.582 \\ 62.786 \end{pmatrix} &\qquad& \bar{\bx}_2 = \begin{pmatrix} 64.761 \\ 60.457 \end{pmatrix} \\
\bS_1 = \begin{pmatrix} 201.04 & 129.56 \\ 129.56 & 316.21 \end{pmatrix} &\qquad& \bS_2 = \begin{pmatrix} 229.88 & 177.02 \\ 177.02 & 354.16 \end{pmatrix}
\end{eqnarray*}
Hence,
\begin{eqnarray*}
\bS_u &=& \frac{1}{98+46-2} \lb 98 \bS_1 + 46 \bS_2 \rb = \begin{pmatrix} 213.21 & 146.76 \\ 146.76 & 332.96 \end{pmatrix}, \\
\bar{\bx}_1 - \bar{\bx}_2 &=& \begin{pmatrix} -4.179 \\ 2.329 \end{pmatrix}, \\
\hat{\bh} &=& \frac{1}{2} (\bar{\bx}_1 + \bar{\bx}_2) = \begin{pmatrix} 62.671 \\ 61.621 \end{pmatrix},
\end{eqnarray*}
and
$$\hat{\ba} = \bS_u^{-1} (\bar{\bx}_1 - \bar{\bx}_2) = \begin{pmatrix} 0.0067 & -0.0030 \\ -0.0030 & 0.0043 \end{pmatrix} \begin{pmatrix} -4.179 \\ 2.329 \end{pmatrix} = \begin{pmatrix} -0.035 \\ 0.022 \end{pmatrix}.$$

The sample ML discriminant rule allocates a new observation\\
 $\bx = (z_1, z_2)^\top$ to $\Pi_1$ if and only if
$$ \hat{\ba}^\top (\bx - \hat{\bh}) = \begin{pmatrix} -0.035 & 0.022 \end{pmatrix} \begin{pmatrix} z_1 - 62.671 \\ z_2 - 61.621 \end{pmatrix} > 0.$$

For example, if a student on this year's course scores 80 on G11PRB and 60 on G11STA then
$$ \hat{\ba}^\top (\bx - \hat{\bh}) = \begin{pmatrix} -0.035 & 0.022 \end{pmatrix} \begin{pmatrix} 80 - 62.671 \\ 60 - 61.621 \end{pmatrix} = -0.644 < 0,$$
and so we would allocate this student to G103.  The boundary, where $\hat{\ba}^\top (\bx - \hat{\bh}) = 0$, is shown below.

FIX
<!--
\begin{center}
\includegraphics[width=12cm,angle=0]{sample_mldr1.pdf}
\end{center}
-->
<!--Note that the boundary line passes half-way between the two sample means.  In this example it is difficult to discriminate accurately between G100 and G103 because there is a large overlap between the two populations.

We could extend the example to include, say, students on GL11.  Here the boundary between the three populations is piece-wise linear and they meet at a common point.

FIX-->
<!--
\begin{center}
\includegraphics[width=12cm,angle=0]{sample_mldr2.pdf}
\end{center}
-->
</div>
</div>
<div id="quadratic-discriminant-analysis-qda" class="section level3">
<h3><span class="header-section-number">2.3.3</span> Quadratic Discriminant Analysis (QDA)</h3>
<p>We have seen that in the case where the populations all share a common covariance matrix, <span class="math inline">\(\boldsymbol{\Sigma}\)</span>, that the decision boundaries are linear (i.e. hyperplanes). We also saw in example <a href="#ex:exnine1"><strong>??</strong></a> in a one-dimensional example that when the two populations had different variances we found a quadratic decision boundary.</p>
<p>In general, if we allow the variances to differ between populations, so that we model <span class="math inline">\(\mathbf x\sim N_p(\mu_k, \boldsymbol{\Sigma}_k)\)</span> for population <span class="math inline">\(k\)</span>, then
we can no longer ignore the determinant of the covariance matrix in the likelihood (see Equation <a href="2-2-lda-ML.html#eq:mvnlike">(2.3)</a>). In this case, the decision rule is
<span class="math display">\[
d(\mathbf x)=\arg\max_k \left(-\frac{1}{2} \log |\boldsymbol{\Sigma}_k| - \frac{1}{2}(\mathbf x-{\boldsymbol{\mu}}_k)^\top \boldsymbol{\Sigma}_k^{-1} (\mathbf x-{\boldsymbol{\mu}}_k)+\log \pi_k\right). \]</span></p>
<p>We cannot ignore the quadratic term in <span class="math inline">\(\mathbf x\)</span> here as it depends upon the population indicator <span class="math inline">\(k\)</span>. Thus in this case we get a quadratic decision boundary rather than a linear one.</p>
<p>The <code>qda</code> function in the <code>MASS</code> package implements quadratic discriminant analysis…..
But you can often get similar result by just including quadratic terms in LDA……..</p>
<div id="iris-example-continued" class="section level4">
<h4><span class="header-section-number">2.3.3.1</span> Iris example continued</h4>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" data-line-number="1">qda.iris &lt;-<span class="st"> </span><span class="kw">qda</span>(Species <span class="op">~</span><span class="st"> </span>Sepal.Length <span class="op">+</span><span class="st"> </span>Sepal.Width <span class="op">+</span><span class="st"> </span>Petal.Length <span class="op">+</span><span class="st"> </span>Petal.Width, iris)</a>
<a class="sourceLine" id="cb52-2" data-line-number="2">qda.iris <span class="co">#s</span></a></code></pre></div>
<pre><code>## Call:
## qda(Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width, 
##     data = iris)
## 
## Prior probabilities of groups:
##     setosa versicolor  virginica 
##  0.3333333  0.3333333  0.3333333 
## 
## Group means:
##            Sepal.Length Sepal.Width Petal.Length Petal.Width
## setosa            5.006       3.428        1.462       0.246
## versicolor        5.936       2.770        4.260       1.326
## virginica         6.588       2.974        5.552       2.026</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1"><span class="kw">partimat</span>(Species <span class="op">~</span><span class="st"> </span>Sepal.Length <span class="op">+</span><span class="st"> </span>Sepal.Width <span class="op">+</span><span class="st"> </span>Petal.Length <span class="op">+</span><span class="st"> </span>Petal.Width, <span class="dt">data=</span>iris, <span class="dt">method=</span><span class="st">&quot;qda&quot;</span>)</a></code></pre></div>
<p><img src="09-lda_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
</div>
</div>
<div id="could-do-prediction-accuracy-here" class="section level3">
<h3><span class="header-section-number">2.3.4</span> Could do prediction accuracy here?</h3>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="2-2-lda-ML.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="2-4-FLDA.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["MultivariateStatistics.pdf"],
"toc": {
"collapse": "section"
},
"pandoc_args": "--top-level-division=[chapter|part]"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
